# simple city naming and renaming system based on Rhye's - edead

from CvPythonExtensions import *
import CvUtil
import Consts as con
from PyHelpers import PyPlayer

gc = CyGlobalContext()

iNumPlayers = con.iNumPlayers

# default names
tCityMap = (
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Glaschu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Beal Feirste",	"Beal Feirste",	"-1",	"-1",	"Luguvalion",	"Luguvalion",	"Coriosopitum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"Gaillimh",	"Gaillimh",	"Ath Cliath",	"-1",	"-1",	"-1",	"Isurium Brigantum",	"Eboracum",	"Eboracum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Gaillimh",	"Ath Cliath",	"-1",	"-1",	"-1",	"Mancunium",	"Mancunium",	"Eboracum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Hafnia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"Corcaigh",	"Loch Garman",	"Loch Garman",	"-1",	"-1",	"Segontium",	"Deva",	"Durobrivae",	"Lindum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Otuken",	"Otuken",	"Otuken",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karabalasagun",	"Karabalasagun",	"Karabalasagun",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"Corcaigh",	"Corcaigh",	"-1",	"-1",	"-1",	"Segontium",	"Uriconium",	"Durobrivae",	"Lindum",	"Venta Icenorum",	"Venta Icenorum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Lirunius",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Otuken",	"Otuken",	"Otuken",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karabalasagun",	"Karabalasagun",	"Karabalasagun",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Maridunum",	"Isca Silurum",	"Glevum",	"Verulamium",	"Londinium",	"Camulodunum",	"Camulodunum",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Flevum Castell",	 "Corbulonis Monumentum",	 "Phabiranum",	 "Jeuphana",	 "Hamburgum",	 "Treva",	 "Virunum",	 "Virunum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bolghar",	"Bolghar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Otuken",	"Otuken",	"Otuken",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karabalasagun",	"Karabalasagun",	"Karabalasagun",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Aquae Solis",	"Verulamium",	"Londinium",	"Londinium",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Flevum Castell",	 "Mediolanium",	 "Tuliphuroum",	 "Tuliphuroum",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Sussudata",	 "Sussudata",	 "Rugium",	 "Sourgum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bolghar",	"Bolghar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Luut",	"Luut",	"Luut",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Isca Dumnoniarum",	"Vindogladia",	"Vindogladia",	"Clausentum",	"Regnum",	"Dubrae",	"Durovernum",	"-1",	"-1",	"-1",	"-1",	 "Ganuenta",	 "Traiectum",	 "Arrenatium",	 "Caeduum",	 "Monasterium",	 "Monasterium",	"-1",	"-1",	"-1",	"-1",	 "Setidava",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karbagatay",	"Karbagatay",	"Karbagatay",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Luut",	"Luut",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tamara",	"Isca Dumnoniarum",	"Isca Dumnoniarum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tornacum",	 "Bruccia",	 "Noviomagus Batavorum",	 "Tricensimae",	 "Dispargum",	 "Monasterium",	 "Monasterium",	"-1",	"-1",	"-1",	 "Calisia",	 "Setidava",	 "Berolinum",	 "Arsicua",	 "Arsicua",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karbagatay",	"Karbagatay",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Luut",	"Luut",	"Luut",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tamara",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gesoriacum",	"Gesoriacum",	"Caletum",	"Bagacum",	 "Atuatuca Tungrorum",	 "Colonia Agrippina",	 "Colonia Agrippina",	 "Alisuen",	 "Segodunum",	 "Tropaea Drusi",	 "Galaegia",	 "Calancorum",	 "Erfordia",	 "Erfordia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Saboci",	 "Saboci",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Karbagatay",	"Karbagatay",	"Karbagatay",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bratuspance",	"Samarobriva",	"Samarobriva",	"Camaracum",	 "Trajectum",	 "Aquae Granni",	 "Confluentes",	 "Bingium",	 "Maniacae Fontes",	 "Melocabus",	 "Lupphurdum",	 "Lupphurdum",	 "Erfordia",	 "Erfordia",	 "Lunioaluem",	 "Arsenium",	 "Arsenium",	 "-1",	 "-1",	 "-1",	 "-1",	 "Asanca",	 "Asanca",	 "Saboci",	 "Saboci",	"Susudava",	 "Netindava",	 "Netindava",	"-1",	"-1",	"-1",	 "-1",	"Sambat",	"Sambat",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sarkel",	"Sarkel",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Constantia",	"-1",	"-1",	"Ratumacos",	"Ratumacos",	"Bratuspance",	"Bratuspance",	"Alaudanum",	"Durocortorum",	 "Aduatuca Tungrorum",	 "Augusta Treverorum",	 "Gelduba",	 "Mogontiacum",	 "Lupodunum",	 "Iocoritum",	 "Gravionrium",	 "Gravionrium",	 "Nomisterum",	 "Budorigum Budorgis",	 "Coridorgis",	 "Phileka",	 "Eburum",	 "Setovia",	 "Asanca",	 "Parienna",	 "Parienna",	 "Asanca",	 "Asanca",	"-1",	"-1",	"Susudava",	 "Netindava",	 "Netindava",	"Arobadara",	"Arobadara",	"-1",	 "-1",	"Sambat",	"Sambat",	"-1",	"-1",	"Gelonus",	"Gelonus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sarkel",	"Sarkel",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Almaliq",	"Almaliq",	"Almaliq",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sanggyeong",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gesocribate",	"Gesocribate",	"Condate",	"-1",	"Constantia",	"Augustodurum",	"Noviomagus",	"Mediolanum Aulercorum",	"Mediolanum Aulercorum",	"Meledunum",	"Caesaromagus",	"Augustomagus",	"Verodunum",	"Verodunum",	"Aquae Granni",	"Aquae Granni",	 "Borbetomagus",	 "Borbetomagus",	 "Bergium",	 "Rhedintovinum",	 "Usbium",	 "Casurgis",	 "Eburodunum",	 "Eburodunum",	 "Parienna",	 "Parienna",	 "Arabum",	 "Singone",	 "Parienna",	 "Parienna",	"-1",	"-1",	 "Samus",	 "Samus",	"-1",	"Susidava",	"Susidava",	"Arobadara",	 "Clepidava",	 "Clepidava",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gelonus",	"Gelonus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Balsaghun",	"Balsaghun",	"Balsaghun",	"Almaliq",	"Almaliq",	"Almaliq",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Turpan",	"Turpan",	"Turpan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sanggyeong",	"Sanggyeong",	"Chaekseong",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Corisopitum",	"Corisopitum",	"Condate",	"Condate",	"Ingena",	"Argentan",	"Argentan",	"Autricum",	"Lutetia",	"Meledunum",	"Maurica",	"Maurica",	"Andematunnum",	 "Divodurum",	 "Divodurum",	 "Tabernae",	 "Borbetomagus",	 "Fon Danuba",	 "Cantiaebis",	 "Bibacum",	 "Bibacum",	 "Casurgis",	"Castra Regina",	"Castra Regina",	 "Marobudum",	 "Medoslanium",	 "Arabum",	 "Singone",	 "Docidava",	 "Docidava",	 "Obrud",	 "Porolissum",	 "Samus",	 "Patridava",	 "Patridava",	"-1",	"Iassiorum",	"Iassiorum",	 "Clepidava",	 "Clepidava",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Atil",	"Atil",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Balsaghun",	"Balsaghun",	"Balsaghun",	"Almaliq",	"Almaliq",	"Almaliq",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Turpan",	"Turpan",	"Turpan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Liao-hsi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Junggyeong",	"Junggyeong",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Darioritum",	"Darioritum",	"Juliomagus",	"Suindinum",	"Suindinum",	"Autricum",	"Eburacon",	"Agedincum",	"Augustobona Tricassium",	"Augustobona Tricassium",	"Andematunnum",	 "Neomagus",	 "Neomagus",	 "Tabernae",	 "Argentoratum",	"Solicinium",	"Bibacum",	 "Setuacatum",	 "Setuacatum",	"Teriolis",	"Castra Regina",	 "Juvavum",	 "Vindobana",	 "Vindobana",	 "Abinta",	 "Abinta",	 "Docidava",	 "Docidava",	 "Obrud",	 "Porolissum",	 "Porolissum",	 "Patridava",	 "Angustia",	 "Angustia",	"-1",	"Iassiorum",	 "Zargidava",	 "Zargidava",	"Ordessus",	"Ordessus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Atil",	"Atil",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Balsaghun",	"Balsaghun",	"Balsaghun",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Turpan",	"Turpan",	"Turpan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Liao-hsi",	"Liao-hsi",	"-1",	"-1",	"Liao-tung",	"Liao-tung",	"Jolbonseong",	"Jolbonseong",	"Jolbonseong",	"Guknaeseong",	"Junggyeong",	"Junggyeong",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Portus Namnetum",	"Portus Namnetum",	"Caesarodunum",	"Caesarodunum",	"Cenabum",	"Cenabum",	"Agedincum",	"Aballo",	"Autissiodorum",	"Alesia",	 "Vesontio",	 "Vesontio",	"Aventicum",	 "Argentoratum",	 "Brigobanne",	 "Brigobanne",	 "Augusta Vindelicum",	"Augusta Vindelicum",	"Teriolis",	"Teriolis",	"-1",	"-1",	"Ovilva",	 "Aquincum",	 "Aquincum",	 "Singidava",	 "Singidava",	 "Ampellum",	 "Napoca",	 "Patavissa",	 "Caput Stenarum",	 "Angustia",	 "Angustia",	"-1",	 "Piroboridava",	 "Zargidava",	 "Zargidava",	"Ordessus",	"Ordessus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tanais",	"Tanais",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Samandar",	"Samandar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kara-khoja",	"Kara-khoja",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Baotou",	"Baotou",	"Hohhot",	"Hohhot",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Liao-tung",	"Liao-tung",	"Jolbonseong",	"Jolbonseong",	"Bonghwangseong",	"Seogyeong",	"Seogyeong",	"-1",	"Donggyeong",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Novioritum",	"Novioritum",	"Caesarodunum",	"Pictavium",	"Vindocinum",	"Nevirnum",	"Bibracte",	"Bibracte",	"Noviodunum",	"Divio",	 "Cabillonum",	 "Equestris Noiodunum",	"-1",	 "Octodurus",	 "Curia Raetorum",	"-1",	 "Cambodunum",	"-1",	"-1",	"-1",	 "Teurnia",	 "Virunum",	 "Sabaria",	 "Sabaria",	 "Sopianae",	 "Singidava",	 "Tibiscum",	 "Tibiscum",	 "Apulon",	 "Apulon",	 "Caput Stenarum",	"-1",	"-1",	 "Comidava",	 "Piroboridava",	 "Piroboridava",	 "Palloda",	 "Palloda",	"Tyras",	"Tyras",	"Olbia Pontike",	"Olbia Pontike",	"Nikonion",	"Nikonion",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Samandar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Cenk",	"-1",	"-1",	"-1",	"-1",	"Otrar",	"Otrar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kara-khoja",	"Kara-khoja",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Baotou",	"Baotou",	"Hohhot",	"Hohhot",	"Pingcheng",	"Pingcheng",	"-1",	"Ji",	"Ji",	"Bohai",	"Bohai",	"Yu-Pei Ping",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Geonan",	"Geonan",	"Bonghwangseong",	"Bonghwangseong",	"Seogyeong",	"Namgyeong",	"Namgyeong",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mediolanum Santonum",	"Angoulesme",	"Pictavium",	"Avaricum",	"Avaricum",	"Matisco",	"Matisco",	"Cabyllona",	"Lugdunum",	 "Lugdunum",	 "Matisco",	"Genava",	"-1",	"-1",	"-1",	"-1",	 "Salurnis",	"-1",	 "Iulium Carnicum",	"-1",	 "Virunum",	 "Segestica",	 "Segestica",	 "Sopianae",	 "Partiscum",	 "Tibiscum",	 "Tibiscum",	 "Sarmizegetusa",	 "Sarmizegetusa",	"-1",	 "Ramidava",	 "Ramidava",	 "Comidava",	 "Polondava",	 "Polondava",	 "Palloda",	 "Palloda",	"Tyras",	"-1",	"-1",	"-1",	"Nikonion",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Balanjar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Cenk",	"-1",	"-1",	"-1",	"-1",	"Otrar",	"Otrar",	"Otrar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tun-huang",	"Tun-huang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kaochue",	"Ping-Cheng",	"Ping-Cheng",	"Yulin",	"Yulin",	"Tinghsiang",	"Tinghsiang",	"Pingcheng",	"Pingcheng",	"Yingmen",	"Ji",	"Ji",	"Bohai",	"Bohai",	"Yu-Pei Ping",	"-1",	"-1",	"-1",	"-1",	"Bisa",	"Bisa",	"-1",	"-1",	"Wanggeomseong",	"Wanggeomseong",	"Wanggeomseong",	"Namgyeong",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mediolanum Santonum",	"Augustoritum",	"Augustoritum",	"Gergovia",	"Gergovia",	"Augusto Nemetum",	"Brivas",	"Ruessium",	"Vienna",	"Vienna",	 "Moriana",	 "Darantasia",	"-1",	 "Oscela",	 "Clavenna",	 "Aquae Bormiae",	 "Tridentum",	 "Tridentum",	 "Aquileia",	 "Aquileia",	"-1",	 "Iulia Aemona",	 "Segestica",	 "Mursa",	 "Partiscum",	 "Argidava",	 "Argidava",	 "Drobeta",	"-1",	 "Rusidava",	"Rusidava",	 "Malva",	"Tirighina",	"Tirighina",	 "Arrubium",	 "Aegyssus",	"-1",	"-1",	"-1",	"Kerkinitis",	"Kerkinitis",	"Kerkinitis",	"-1",	"-1",	"-1",	"-1",	"Phanagoreia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Balanjar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Otrar",	"Otrar",	"Otrar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kashgar",	"Kashgar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tun-huang",	"Tun-huang",	"Tun-huang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kaochue",	"Ping-Cheng",	"Ping-Cheng",	"Yulin",	"Yulin",	"Tinghsiang",	"-1",	"-1",	"Yingmen",	"Yingmen",	"-1",	"Hochien",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bisa",	"-1",	"-1",	"-1",	"-1",	"Wanggeomseong",	"Wonsanjin",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Burdigala",	"Burdigala",	"Vesunna",	"Vesunna",	"Augusto Nemetum",	"Augusto Nemetum",	"Brivas",	"Ruessium",	"Valentia Julia",	"Valentia Julia",	 "Ebrodunum",	"-1",	 "Eporedia",	 "Mediolanum",	 "Mediolanum",	 "Brixia",	 "Verona",	 "Altinum",	 "Aquileia",	 "Aquileia",	 "Tergeste",	 "Iulia Aemona",	 "Iulia Aemona",	 "Mursa",	 "Singidunum",	 "Singidunum",	 "Argidava",	 "Drobeta",	 "Drobeta",	 "Sucidava",	 "Malva",	 "Malva",	 "Tiasum",	 "Nentidava",	 "Arrubium",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chersonesos",	"Chersonesos",	"Theodosia",	"Theodosia",	"-1",	"Phanagoreia",	"Phanagoreia",	"Torik",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tureng Tepe",	"Tureng Tepe",	"-1",	"-1",	"-1",	"-1",	"-1",	"Urgench",	"Urgench",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khujand",	"Kokand",	"Kokand",	"Osh",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tun-huang",	"-1",	"-1",	"Lufu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Shofang",	"Shofang",	"Shang",	"Shang",	"Loufan",	"-1",	"-1",	"-1",	"Hengshan",	"-1",	"Hochien",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Naemihol",	"Naemihol",	"Wonsanjin",	"Wonsanjin",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Burdigala",	"Burdigala",	"Aginnum",	"Aginnum",	"Segodunum",	"Segodunum",	"Millau",	"Millau",	"Arelate",	"Arelate",	 "Ebrodunum",	"-1",	 "Augusta Taurinorum",	 "Mediolanum",	 "Mediolanum",	 "Cremona",	 "Mantua",	 "Patavium",	"-1",	"-1",	 "Tergeste",	 "Tarsatica",	 "Tarsatica",	 "Delminium",	 "Sirmium",	 "Singidunum",	 "Viminacium",	 "Viminacium",	 "Ratiaria",	 "Ratiaria",	 "Sucidava",	 "Tiasum",	 "Tiasum",	 "Nentidava",	 "Tomi",	 "Tomi",	"-1",	"-1",	"-1",	"-1",	"Chersonesos",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dioskourias",	"Dioskourias",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Urgench",	"Urgench",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khujand",	"Khujand",	"Kokand",	"Kokand",	"Osh",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lufu",	"-1",	"Lude",	"-1",	"Liangzhou",	"Liangzhou",	"-1",	"-1",	"-1",	"Shofang",	"Shofang",	"Shang",	"Shang",	"Loufan",	"Loufan",	"-1",	"Hengshan",	"Hengshan",	"Chingho",	"Hochien",	"Tianjin",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Naemihol",	"Naemihol",	"Hanseong",	"Hanseong",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lapurdum",	"Elusa",	"Tolosa",	"Tolosa",	"Narbo",	"Narbo",	"Baetarnae",	"Nemausus",	"Arelate",	 "Arelate",	 "Aquae Sextiae",	"-1",	 "Portus Maurici",	 "Genua",	 "Genua",	 "Luna",	 "Mutina",	 "Ravenna",	"-1",	"-1",	 "Pola",	"-1",	 "Salonae",	 "Delminium",	 "Ulpiana",	 "Ulpiana",	 "Naissus",	 "Naissus",	 "Serdica",	 "Serdica",	 "Novae",	 "Novae",	 "Durostorum",	 "Durostorum",	 "Marcianopolis",	 "Tomi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pazisi",	"Pazisi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khiva",	"Khiva",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khujand",	"Khujand",	"Kokand",	"Kokand",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khotan",	"Khotan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lude",	"-1",	"Guwei",	"Guwei",	"Liangzhou",	"Gu-zan",	"Gu-zan",	"Gu-zan",	"Shangho",	"Shangho",	"Fushi",	"Fushi",	"Jin-yang",	"Jin-yang",	"Jin-yang",	"Jin-yang",	"Chingho",	"Chingho",	"Hochien",	"Tianjin",	"Tianjin",	"-1",	"-1",	"-1",	"-1",	"Yantai",	"Yantai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hanseong",	"Wiryeseong",	"Siljilguk",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lapurdum",	"Augusta Ausciorum",	"Tolosa",	"Tolosa",	"Narbo",	"Narbo",	"-1",	"-1",	"-1",	 "Massilia",	 "Aquae Sextiae",	 "Antipolis",	"-1",	"-1",	"-1",	 "Pisae",	 "Arretium",	 "Ravenna",	"-1",	"-1",	"-1",	"-1",	 "Salonae",	 "Spalatum",	 "Spalatum",	"-1",	 "Scupi",	 "Scupi",	 "Serdica",	"-1",	 "Novae",	"Nicopolis ad Istrum",	"Nicopolis ad Istrum",	 "Marcianopolis",	 "Marcianopolis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pazisi",	"Kutatisi",	"Urbnisi",	"-1",	"-1",	"-1",	"Albana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khiva",	"Dargan Ata",	"Dargan Ata",	"-1",	"-1",	"-1",	"-1",	"-1",	"Samarkand",	"Samarkand",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Khotan",	"Khotan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Guwei",	"-1",	"Gu-zan",	"Gu-zan",	"Shangho",	"Beidi",	"Beidi",	"Fushi",	"Jin-yang",	"Jin-yang",	"Jin-yang",	"Jin-yang",	"Chao",	"Handan",	"Handan",	"Pingyuan",	"Chienchang",	"Linzi",	"Linzi",	"-1",	"Donglai",	"Yantai",	"Yantai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Wiryeseong",	"Wiryeseong",	"Siljilguk",	"-1",	),
(	"-1",	"-1",	"Brigantium",	"Lucus Augusti",	"-1",	"Lancia",	"-1",	"Portus Victoriae",	"Portus Victoriae",	"Pompaelo",	"-1",	"-1",	"-1",	"Gerunda",	"Gerunda",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Vetulonium",	 "Vetulonium",	 "Arretium",	 "Ancona",	"-1",	"-1",	"-1",	"-1",	 "Spalatum",	 "Spalatum",	"Dioclea",	"-1",	 "Scupi",	"-1",	 "Philippopolis",	 "Philippopolis",	 "Hadrianopolis",	 "Hadrianopolis",	 "Arcadiopolis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Apsaros",	"Pazisi",	"Urbnisi",	"Vagharshapat",	"Vagharshapat",	"Kabalaka",	"-1",	"Albana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dargan Ata",	"Dargan Ata",	"Buchara",	"Buchara",	"Buchara",	"Karmana",	"Karmana",	"Samarkand",	"Samarkand",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Huanchung",	"Huanchung",	"Huanchung",	"Jincheng",	"Jincheng",	"Lingchu",	"Lingchu",	"Beidi",	"Beidi",	"Hedong",	"Hedong",	"Anyi",	"Anyi",	"-1",	"Chao",	"Handan",	"Handan",	"Pingyuan",	"Chienchang",	"Linzi",	"-1",	"Donglai",	"Donglai",	"Jimo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sabi",	"Sabi",	"Geumseong",	"-1",	),
(	"-1",	"Brigantium",	"Brigantium",	"-1",	"Bracara Augusta",	"-1",	"Legio",	"Clunia",	"Clunia",	"Augusta Bilbilis",	"Turiaso",	"Osca",	"Osca",	"-1",	"Emporiae",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Aleria",	"-1",	"-1",	"Roma",	"Roma",	"Capua",	"Spoleto",	"-1",	"-1",	"-1",	"-1",	 "Scodra",	"Dioclea",	 "Stobi",	 "Stobi",	"Siris",	"-1",	 "Philippopolis",	 "Hadrianopolis",	 "Hadrianopolis",	 "Arcadiopolis",	 "Arcadiopolis",	"-1",	"-1",	"-1",	"-1",	"-1",	"Amastris",	"Amastris",	"Sinope",	"Sinope",	"-1",	"-1",	"-1",	"-1",	"-1",	"Rhizos",	"-1",	"-1",	"-1",	"Vagharshapat",	"Kabalaka",	"Kabalaka",	 "Tchor",	 "Tchor",	"Kamachia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chardjui",	"Buchara",	"Buchara",	"Karmana",	"Karmana",	"Nautaka",	"Nautaka",	"Demetrias",	"-1",	"Alexandreia Oxiani",	"Alexandreia Oxiani",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mani",	"Mani",	"Mani",	"Chuucnar",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hsihai",	"Huanchung",	"Huanchung",	"Hokuan",	"Jincheng",	"Jincheng",	"Lingchu",	"Lingchu",	"Anting",	"Anting",	"Hedong",	"Hedong",	"Anyi",	"Anyi",	"Anyi",	"Tung",	"Tung",	"Taho",	"Taho",	"-1",	"-1",	"-1",	"Chi",	"Qiaohsi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sabi",	"Sabi",	"-1",	"-1",	),
(	"-1",	"Portus Cale",	"-1",	"Castra Leuca",	"Salamantica",	"Salamantica",	"Termes",	"Termes",	"-1",	"Salduie",	"Salduie",	"Azaila",	"Cissis",	"Cissis",	"Barcino",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Aleria",	"-1",	"-1",	"-1",	"Roma",	"Capua",	"Capua",	"Beneventum",	"-1",	"-1",	"-1",	"Scodra",	"Scodra",	"Herakleia Lynkestis",	"Herakleia Lynkestis",	 "Pella",	 "Pella",	"Philippoi",	"Philippoi",	 "Hadrianopolis",	"Trajanopolis",	"Trajanopolis",	 "Byzantion",	"-1",	"-1",	"Herakleia Pontike",	"Herakleia Pontike",	"Amastris",	"-1",	"Sinope",	"Amaseia",	"Kabeira",	"Kabeira",	"Trapezous",	"Trapezous",	"Rhizos",	"-1",	"Zarishat",	"Armavir",	"Artashat",	"Artashat",	"Dvin",	"-1",	 "Tchor",	 "Tchor",	"Kamachia",	"Kamachia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chardjui",	"Chardjui",	"-1",	"-1",	"-1",	"Baktra",	"Demetrias",	"Demetrias",	"Drapsaka",	"Alexandreia Oxiani",	"Alexandreia Oxiani",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mani",	"Mani",	"Mani",	"Chuucnar",	"-1",	"-1",	"-1",	"-1",	"Hsihai",	"Hsihai",	"Chiaoho",	"Hokuan",	"Hokuan",	"Didao",	"Didao",	"Didao",	"Tianshui",	"Tianshui",	"Anting",	"Chang'an",	"Chang'an",	"Gaoling",	"Luoyang",	"Luoyang",	"Luoyang",	"Kaifeng",	"Shanyang",	"Shanyang",	"-1",	"Qufu",	"-1",	"Chi",	"Donghai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"Conimbriga",	"Conimbriga",	"Castra Leuca",	"Castra Leuca",	"Salamantica",	"-1",	"Segovia",	"Complutum",	"-1",	"Segontia",	"Salduie",	"Dertosa",	"Dertosa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Neapolis",	"Neapolis",	"Beneventum",	"Ausculum",	"-1",	"-1",	"-1",	"Dyrrachium",	"Dyrrachium",	 "Heraclea",	 "Pella",	 "Pella",	"Philippoi",	"-1",	"-1",	"-1",	"-1",	"-1",	"Nikomedeia",	"Nikomedeia",	"Herakleia Pontike",	"Ancyra",	"Ancyra",	"Gangra",	"-1",	"Amaseia",	"Amaseia",	"-1",	"-1",	"-1",	"-1",	"Karin",	"Zarishat",	"Armavir",	"Artashat",	"-1",	"Dvin",	"-1",	"Tauris",	"Artavil",	"Artavil",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Nisa",	"Nisa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Baktra",	"Baktra",	"Drapsaka",	"Drapsaka",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Zhikharkhunglung",	"Zhikharkhunglung",	"Khyetenshering",	"Khyetenshering",	"Tashi Gonpa",	"Tashi Gonpa",	"-1",	"-1",	"-1",	"Chiaoho",	"-1",	"-1",	"Lunghsi",	"Lunghsi",	"Hanchung",	"Tianshui",	"Fangling",	"Fangling",	"Chang'an",	"Chang'an",	"Gaoling",	"Hongnong",	"Luoyang",	"Luoyang",	"Kaifeng",	"Kaifeng",	"Shanyang",	"-1",	"-1",	"-1",	"Chu",	"Donghai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"Conimbriga",	"Collippo",	"Horta Navia",	"Norba Caesarina",	"-1",	"Toletum",	"Toletum",	"Segobriga",	"Ercavica",	"-1",	"Saguntum",	"Saguntum",	"-1",	"-1",	"-1",	"-1",	"Mago",	"-1",	"-1",	"-1",	"-1",	"-1",	"Olbia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Neapolis",	"Heraclea",	"Tarentum",	"-1",	"-1",	"Dyrrachium",	"Dyrrachium",	"-1",	"Larissa",	"-1",	"-1",	"-1",	"-1",	"Abydos",	"Abydos",	"Prousa",	"Nikaia",	"Nikaia",	"Dorylaion",	"Ancyra",	"Ancyra",	"Gangra",	"Caesarea",	"Caesarea",	"Sevasteia",	"Sevasteia",	"Malateia",	"Malateia",	"Arshamashat",	"Tigranakert",	"Tigranakert",	"Manavazkert",	"-1",	"Owrmia",	"Partaw",	"Tauris",	"Tauris",	"Artavil",	"Kouton",	"-1",	"-1",	"-1",	"-1",	"Zadrakarta",	"-1",	"Nisa",	"Nisa",	"-1",	"Merv",	"Merv",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lumaringbo",	"Lumaringbo",	"Thogdorogpa",	"Thogdorogpa",	"-1",	"-1",	"-1",	"Zhikharkhunglung",	"Zhikharkhunglung",	"Khyetenshering",	"Khyetenshering",	"Tashi Gonpa",	"Tashi Gonpa",	"-1",	"-1",	"Thongphu",	"-1",	"-1",	"-1",	"-1",	"Lunghsi",	"Hanchung",	"Hanchung",	"Fangling",	"-1",	"Shanglo",	"Shanglo",	"Hsiangheng",	"Hsiangheng",	"Hsiangheng",	"Nanyang",	"Nanyang",	"Liang",	"Liang",	"Chu",	"Chu",	"-1",	"Shouchun",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hakata",	),
(	"-1",	"Olisipo",	"Ammaia",	"Emerita Augusta",	"Metellinum",	"Toletum",	"Toletum",	"Libisosa",	"Ercavica",	"Ercavica",	"Valentia",	"Saguntum",	"-1",	"-1",	"-1",	"Palmaria",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bosa",	"Olbia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Thurii",	"-1",	"Brundisium",	"-1",	"Nicopolis",	"Nicopolis",	"Naupaktos",	"-1",	"Larissa",	"-1",	"-1",	"-1",	"Abydos",	"Abydos",	"Prousa",	"Prousa",	"Dorylaion",	"Dorylaion",	"Ikonion",	"Ikonion",	"-1",	"Caesarea",	"Caesarea",	"Sevasteia",	"Sevasteia",	"-1",	"-1",	"Carrhae",	"-1",	"Tigranakert",	"-1",	"-1",	"Owrmia",	"Partaw",	"-1",	"Gazaka",	"Phraaspa",	"Kouton",	"Kouton",	"Amui",	"Amui",	"Zadrakarta",	"Zadrakarta",	"-1",	"-1",	"Sousia",	"Sousia",	"Merv",	"Merv",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Rajavasa",	"Rajavasa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lumaringbo",	"Lumaringbo",	"-1",	"Thogdorogpa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Thongphu",	"-1",	"-1",	"Lintao",	"Lintao",	"Chiaming",	"-1",	"Hanchung",	"Hsicheng",	"Hanzhong",	"Hanzhong",	"Shanglo",	"Shanglo",	"Hsiangheng",	"Hsiangheng",	"Nanyang",	"Nanyang",	"Huaiyang",	"Liang",	"Chu",	"Chu",	"Shouchun",	"Shouchun",	"Linhuai",	"Linhuai",	"Guangling",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"Olisipo",	"Evora",	"Emerita Augusta",	"Metellinum",	"Corduba",	"Corduba",	"Libisosa",	"Villarrobledo",	"Villarrobledo",	"Valentia",	"Valentia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tharros",	"Karalis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Consentia",	"-1",	"-1",	"-1",	"-1",	"Nicopolis",	"Naupaktos",	"Naupaktos",	"Thebai",	"Thebai",	"-1",	"-1",	"Smyrna",	"Smyrna",	"Sardis",	"Sardis",	"Nikopolis",	"Pessinous",	"Ikonion",	"Tyana",	"Nazianzos",	"Nazianzos",	"-1",	"-1",	"-1",	"Germanikeia",	"Apameia",	"Apameia",	"Edessa",	"Edessa",	"Nisibis",	"Nisibis",	"Arbela",	"Arbela",	"Gazaka",	"Phraaspa",	"Phraaspa",	"-1",	"-1",	"-1",	"-1",	"Rhagai",	"Hecatompylos",	"Hecatompylos",	"-1",	"Sousia",	"Sousia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kapisa",	"Kapisa",	"-1",	"Pushklavati",	"Rajavasa",	"Rajavasa",	"Jalham",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Thogjalung",	"Thogjalung",	"Mendong Gonpa",	"Mendong Gonpa",	"Umbu",	"Umbu",	"Shensa Dsong",	"Shensa Dsong",	"Nagchu Dsong",	"Nagchu Dsong",	"-1",	"-1",	"-1",	"-1",	"-1",	"Garze",	"Minshan",	"-1",	"-1",	"Chiaming",	"Chiaming",	"-1",	"Hanzhong",	"Hanzhong",	"Hsicheng",	"Hsicheng",	"-1",	"Hsiangyang",	"Hsiangyang",	"Yuan",	"Yuan",	"-1",	"Wuchang",	"Liuan",	"Shouchun",	"Shouchun",	"Luchiang",	"Jianye",	"Jianye",	"Hailing",	"Guangling",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"Mirobriga",	"Pax Julia",	"Italica",	"Hispalis",	"Corduba",	"Corduba",	"Beatia",	"Beatia",	"Abdera",	"Abdera",	"Lucentum",	"Lucentum",	"-1",	"Iboshim",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Panormus",	"Panormus",	"Agrigentum",	"-1",	"-1",	"Rhegium",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Korinthos",	"Athinai",	"-1",	"-1",	"-1",	"-1",	"Ephesos",	"Ephesos",	"Sardis",	"-1",	"Perge",	"Korakesion",	"Tyana",	"Tyana",	"-1",	"Tarsos",	"Antiocheia tes Kilikias",	"Antiocheia tes Kilikias",	"Germanikeia",	"Apameia",	"Apameia",	"Edessa",	"Edessa",	"Nisibis",	"Nisibis",	"Arbela",	"Arbela",	"-1",	"-1",	"Shad Shahpur",	"Shad Shahpur",	"Arsacia",	"Arsacia",	"Rhagai",	"Rhagai",	"Hecatompylos",	"Hecatompylos",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kapul",	"-1",	"-1",	"-1",	"Pushklavati",	"Taxila",	"Jalham",	"Jalham",	"Sakala",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Thogjalung",	"Thogjalung",	"Mendong Gonpa",	"Mendong Gonpa",	"-1",	"-1",	"Shensa Dsong",	"Shensa Dsong",	"Nagchu Dsong",	"Nagchu Dsong",	"-1",	"Shodu",	"Shodu",	"Draya",	"-1",	"-1",	"Chiaming",	"Minshan",	"Garze",	"Kuanghang",	"Minshan",	"Minshan",	"Hsi'cheng",	"Hsi'cheng",	"-1",	"Hsicheng",	"Hsicheng",	"Iling",	"Iling",	"Ying",	"Ying",	"Wuchang",	"-1",	"-1",	"-1",	"-1",	"Hwaining",	"Jianye",	"Jianye",	"Wuxi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"Pax Julia",	"Ossonoba",	"Onuba Aestuaria",	"Hispalis",	"Castulo",	"Castulo",	"-1",	"Abdera",	"Qart Hadasht",	"Qart Hadasht",	"Lucentum",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Agrigentum",	"Agrigentum",	"Messana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Elis",	"Elis",	"Korinthos",	"-1",	"Athinai",	"-1",	"-1",	"Halicarnasus",	"Halicarnasus",	"Kaunos",	"-1",	"Perge",	"Perge",	"Korakesion",	"-1",	"-1",	"Tarsos",	"Tarsos",	"-1",	"-1",	"Antiochia",	"Beroea",	"Kallinikos",	"Kallinikos",	"Circesium",	"Circesium",	"Mepsila",	"Mepsila",	"Assour",	"-1",	"Kallone",	"Kallone",	"Ecbatana",	"Arsacia",	"Arsacia",	"Saavakineh",	"Semina",	"Semina",	"-1",	"-1",	"-1",	"-1",	"-1",	"Alexandreia Ariana",	"Alexandreia Ariana",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gazna",	"Gazna",	"-1",	"-1",	"-1",	"-1",	"Taxila",	"Taxila",	"Sakala",	"Sakala",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Barkha",	"Barkha",	"Sakha Dsong",	"Sakha Dsong",	"Zhigatse",	"Zhigatse",	"Lhasa",	"Lhasa",	"-1",	"Gyamda Dsong",	"-1",	"Draya",	"Draya",	"-1",	"-1",	"-1",	"-1",	"Shu",	"Maoniu",	"Shu",	"Shu",	"Hsi'cheng",	"Jiangzhou",	"Jiangzhou",	"Yicheng",	"Yicheng",	"Iling",	"Iling",	"Ying",	"Ying",	"-1",	"Ezhou",	"Ezhou",	"-1",	"Hwaining",	"Hwaining",	"Sui'an",	"Sui'an",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"Cilpes",	"Ossonoba",	"Ossonoba",	"Gadir",	"Gadir",	"Castulo",	"Antikeria",	"-1",	"Qart Hadasht",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hippo Diarrhytos",	"-1",	"-1",	"-1",	"-1",	"-1",	"Agrigentum",	"Syrakousai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sparta",	"Sparta",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kaunos",	"Kaunos",	"Myra",	"-1",	"-1",	"Seleukeia Tracheotis",	"Seleukeia Tracheotis",	"-1",	"-1",	"-1",	"Antiochia",	"Antiochia",	"Beroea",	"Kallinikos",	"Circesium",	"Circesium",	"Dura",	"Mepsila",	"Assour",	"Assour",	"-1",	"Kallone",	"Kallone",	"Ecbatana",	"Ecbatana",	"Saavakineh",	"Saavakineh",	"Semina",	"Semina",	"-1",	"-1",	"-1",	"-1",	"-1",	"Alexandreia Ariana",	"Alexandreia Ariana",	"Phra",	"-1",	"-1",	"-1",	"-1",	"Gazna",	"Gazna",	"-1",	"-1",	"-1",	"-1",	"-1",	"Divyakutta",	"Divyakutta",	"Lavapuri",	"Kurukshetra",	"Kurukshetra",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sakha Dsong",	"Sakha Dsong",	"Zhigatse",	"Zhigatse",	"Lhasa",	"Lhasa",	"Gyamda Dsong",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Shu",	"Litang",	"Ba",	"Shu",	"Shu",	"Jiangyang ",	"Jiangzhou",	"Jiangzhou",	"Yicheng",	"Yicheng",	"Ying",	"Jiangling",	"Lingchang",	"Lingchang",	"-1",	"Ezhou",	"-1",	"-1",	"Hofei",	"Hofei",	"Sui'an",	"Sui'an",	"Kuaiji",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Gadir",	"-1",	"Ronda",	"-1",	"Antikeria",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Russucurrum",	"Russucurrum",	"Rusicade",	"Rusicade",	"Thabraca",	"Utica",	"Utica",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sparta",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Byblos",	"Byblos",	"Palmyra",	"Casama",	"Casama",	"Dura",	"Dura",	"Zeitha",	"Birtha",	"Birtha",	"Seleukeia tou Hedyphon",	"-1",	"Vagistana",	"Vagistana",	"Laodikeia",	"Laodikeia",	"Kom",	"Kom",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Phra",	"Phra",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Arithapuri",	"Arithapuri",	"Divyakutta",	"Lavapuri",	"Lavapuri",	"Kurukshetra",	"Kurukshetra",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chingyang",	"Jiangyang ",	"Jiangyang ",	"Fuling",	"Fuling",	"Chingchiang",	"Liyang",	"Wuling",	"-1",	"-1",	"-1",	"Chianghsia",	"Yuchang",	"Nanchang",	"-1",	"Chiuchiang",	"Chiuchiang",	"-1",	"Hsin'an",	"Kuaiji",	"Kuaiji",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Baelo Claudia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Iol",	"Icosium",	"Icosium",	"Zarai",	"Zarai",	"Tzirta",	"Tzirta",	"Thabraca",	"Utica",	"Qart-Hadasht",	"-1",	"Clupea",	"-1",	"-1",	"Malta",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gortyna",	"Cnossos",	"Cnossos",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kyrenia",	"Salamis",	"Trachonas",	"-1",	"-1",	"Sidon",	"-1",	"Damascus",	"Palmyra",	"Dionysias",	"Anatho",	"Anatho",	"Zeitha",	"Zeitha",	"Seleucia",	"Seleucia",	"Artemita",	"Artemita",	"-1",	"Vagistana",	"Laodikeia",	"Laodikeia",	"Ispadana",	"-1",	"Ispadana",	"-1",	"-1",	"-1",	"-1",	"-1",	"Zranka",	"Qandahar",	"Qandahar",	"Qandahar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Arithapuri",	"Arithapuri",	"-1",	"Lavapuri",	"Prasthala",	"Prasthala",	"Indraprastha",	"Indraprastha",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chingyang",	"Lufing",	"Fuling",	"Chingyang",	"Lufing",	"Fuling",	"Fuling",	"Chingchiang",	"Liyang",	"Wuling",	"Wuling",	"-1",	"-1",	"Ch'ang-sha",	"Yuchang",	"Nanchang",	"Nanchang",	"Chiuchiang",	"-1",	"Hsin'an",	"Hsin'an",	"Tung'an",	"Tung'an",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Iol",	"Iol",	"Cartennae",	"Vescera",	"Vescera",	"Zarai",	"Tzirta",	"-1",	"Hadrumetum",	"Hadrumetum",	"Hadrumetum",	"Clupea",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Paphos",	"Kourion",	"-1",	"-1",	"-1",	"Tyre",	"Paneias",	"Damascus",	"Damascus",	"Dionysias",	"-1",	"Anatho",	"Nehardea",	"Nehardea",	"Seleucia",	"Seleucia",	"Artemita",	"Kelonae",	"-1",	"-1",	"Borugerd",	"Borugerd",	"Ispadana",	"Ispadana",	"Ysatis",	"Ysatis",	"-1",	"-1",	"-1",	"-1",	"Zranka",	"Qandahar",	"Qandahar",	"Qandahar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Multan",	"Multan",	"-1",	"-1",	"-1",	"Prasthala",	"Prasthala",	"Indraprastha",	"Indraprastha",	"Etmadpur",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Yuehsiu",	"Yuehsiu",	"-1",	"-1",	"Lufing",	"Lufing",	"-1",	"Chien'an",	"-1",	"Guiyang",	"-1",	"Qiangzhong",	"Qiangzhong",	"-1",	"-1",	"Ch'ang-sha",	"Ch'ang-sha",	"I'chun",	"Qianzhou",	"Qianzhou",	"Chien'an",	"Chien'an",	"-1",	"Yung'chia",	"Yung'chia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Tingis",	"-1",	"-1",	"-1",	"-1",	"Siga",	"Siga",	"Cartennae",	"Cartennae",	"-1",	"-1",	"Gemellae",	"Gemellae",	"-1",	"Ad Majores",	"Ad Majores",	"-1",	"Tbessa",	"Tbessa",	"Sbrt'n",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tyre",	"Paneias",	"Bostra",	"Bostra",	"-1",	"-1",	"-1",	"Nehardea",	"Babylon",	"Babylon",	"Apameia",	"Apameia",	"Akra",	"Akra",	"Susa",	"-1",	"Borugerd",	"Pasargadae",	"Pasargadae",	"Ysatis",	"Ysatis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mulashthanapura",	"Multan",	"Multan",	"-1",	"-1",	"-1",	"Upaplavya",	"Upaplavya",	"Mathura",	"Mathura",	"Etmadpur",	"Etmadpur",	"Ayodhya",	"Kusinagara",	"Kusinagara",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Deqin",	"-1",	"-1",	"Dali",	"Lijang",	"-1",	"-1",	"Zhaotang",	"Zhaotang",	"Zhaotang",	"Guiyang",	"Guiyang",	"-1",	"Qiangzhong",	"Qiangzhong",	"Hengshan",	"Hengshan",	"Hengzhou ",	"Hengzhou ",	"I'chun",	"Qianzhou",	"Qianzhou",	"Chien'an",	"Chien'an",	"Dongye",	"-1",	"Yung'chia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"Lixus",	"Tingis",	"Rusadir",	"Rusadir",	"Rusadir",	"Siga",	"Siga",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dimmidi",	"Dimmidi",	"Tbessa",	"Tbessa",	"Tbessa",	"Tbessa",	"Sbrt'n",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Akre",	"Akre",	"Scythopolis",	"Bostra",	"Bostra",	"-1",	"-1",	"-1",	"-1",	"Babylon",	"Babylon",	"Apameia",	"Apameia",	"Akra",	"Akra",	"Susa",	"Susa",	"-1",	"Pasargadae",	"Pasargadae",	"Karmana",	"Karmana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Aror",	"Aror",	"-1",	"Mulashthanapura",	"Mulashthanapura",	"-1",	"-1",	"-1",	"-1",	"Upaplavya",	"Upaplavya",	"Mathura",	"Mathura",	"Kampilya",	"Kannauj",	"Ayodhya",	"Ayodhya",	"Alipur",	 "Sasaram",	 "Sasaram",	"Vaishali",	"Vaishali",	"-1",	"-1",	"-1",	"Pragjyotishpur",	"-1",	"-1",	"-1",	"-1",	"Deqin",	"Deqin",	"-1",	"Dali",	"-1",	"-1",	"-1",	"Zhaotang",	"-1",	"Zhaotang",	"Tsangke",	"-1",	"-1",	"-1",	"Lingling",	"Lingling",	"Kueiyang",	"Hengzhou ",	"Hengzhou ",	"Nankang",	"Luling",	"-1",	"-1",	"-1",	"Dongye",	"Dongye",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"Lixus",	"Lixus",	"Volubilis",	"Volubilis",	"Rusadir",	"-1",	"Siga",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dimmidi",	"Dimmidi",	"Tbessa",	"Tbessa",	"Tbessa",	"Tbessa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kaisareia",	"Scythopolis",	"Scythopolis",	"Philadelphia",	"Philadelphia",	"-1",	"-1",	"-1",	"-1",	"Borsippa",	"Borsippa",	"Orchoe",	"Orchoe",	"Apphadana",	"Apphadana",	"Aginis",	"Aginis",	"Dezjpul",	"-1",	"-1",	"-1",	"Karmana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sehwan",	"Sehwan",	"Aror",	"-1",	"Bahawalpuri",	"Bahawalpuri",	"-1",	"-1",	"-1",	"-1",	"Viratanagara",	"Vairata",	"Vairata",	"Agrevana",	"Kannauj",	"Prayaga",	"-1",	"-1",	"-1",	"-1",	 "Sasaram",	"Pataliputra",	"Pataliputra",	 "Paundra",	"-1",	"Pragjyotishpur",	"Pragjyotishpur",	"-1",	"-1",	"-1",	"-1",	"-1",	"Darllit",	"Mengmao",	"Mengmao",	"-1",	"-1",	"Darllit",	"Sit Cat",	"Sit Cat",	"-1",	"Tsangke",	"Tsangke",	"-1",	"-1",	"Lingling",	"Lingling",	"Kueiyang",	"Kueiyang",	"Nankang",	"Nankang",	"Luling",	"Luling",	"-1",	"Tong'an",	"Tong'an",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"Rutubis",	"Sala Colonia",	"Sala Colonia",	"Volubilis",	"Volubilis",	"Pomaria",	"Pomaria",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sbrt'n",	"Sbrt'n",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gaza",	"Kaisareia",	"Jerusalem",	"-1",	"Philadelphia",	"Philadelphia",	"-1",	"-1",	"-1",	"-1",	"-1",	"Borsippa",	"Orchoe",	"Charax Spasinou",	"-1",	"-1",	"Aginis",	"Aginis",	"-1",	"-1",	"Parsa",	"-1",	"Alexandreia Carmaneia",	"Alexandreia Carmaneia",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sehwan",	"Sehwan",	"-1",	"-1",	"Bahawalpuri",	"Bahawalpuri",	"-1",	"-1",	"-1",	"-1",	"Viratanagara",	"Vairata",	"Vairata",	"Agrevana",	"Padmavati",	"Prayaga",	"-1",	"-1",	"Varanasi",	"-1",	 "Navadwipa",	"Pataliputra",	"Rajagrha",	 "Lakshmanavati",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Darllit",	"-1",	"Tengzhong",	"Tengzhong",	"-1",	"Lincang",	"Sit Cat",	"Sit Cat",	"-1",	"Nanning",	"Nanning",	"-1",	"-1",	"Yulin",	"Yulin",	"Guangxin",	"Guangxin",	"Hsi'ping",	"Hsi'ping",	"-1",	"Chieh-yang",	"Shantou",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"Arambys",	"Arambys",	"Rutubis",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pomaria",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sbrt'n",	"Sbrt'n",	"Oea",	"Leptis Magna",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ptolemaida",	"Cyrene",	"Darnis",	"Antipyrgus Portus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Naukratis",	"Naukratis",	"Tanis",	"-1",	"-1",	"Gaza",	"Gaza",	"Bersabee",	"Bersabee",	"-1",	"Sela",	"Sela",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Charax Spasinou",	"Charax Spasinou",	"-1",	"-1",	"Hieralis",	"Hieralis",	"-1",	"-1",	"-1",	"Alexandreia Carmaneia",	"Alexandreia Carmaneia",	"-1",	"Poura",	"Poura",	"-1",	"-1",	"Turbat",	"Turbat",	"-1",	"-1",	"Pattala",	"Pattala",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ajmer",	"Ajmer",	"Gwalior",	"Gwalior",	"Kausambi",	"Kausambi",	"Mizrapuri",	"-1",	"-1",	"-1",	"Nalanda",	"Rajagrha",	"Rajagrha",	 "Lakshmanavati",	"Kolikata",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tengzhong",	"Tengzhong",	"Lincang",	"Lincang",	"Twen Hia",	"Twen Hia",	"Cao Hanh",	"Cao Hanh",	"Nanning",	"-1",	"Hob Pho",	"Yulin",	"Yulin",	"Guangxin",	"Guangxin",	"Panyu",	"Panyu",	"Chieh-yang",	"Chieh-yang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"Rhysaddir",	"Rhysaddir",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Oea",	"Oea",	"Leptis Magna",	"Leptis Magna",	"Thubactis",	"Thubactis",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ptolemaida",	"Cyrene",	"Darnis",	"Antipyrgus Portus",	"Antipyrgus Portus",	"Ardanis Portus",	"-1",	"-1",	"-1",	"-1",	"-1",	"Alexandreia",	"Alexandreia",	"Athribis",	"Tanis",	"Pelusion",	"Pelusion",	"Klysma",	"Klysma",	"Bersabee",	"Aelana",	"Aelana",	"Sela",	"Sela",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ikaros",	"Ikaros",	"-1",	"-1",	"Hieralis",	"Apostona",	"Apostona",	"Oarakeia",	"Oarakeia",	"Harmozia",	"Harmozia",	"Dagaseira",	"Poura",	"Poura",	"-1",	"-1",	"Turbat",	"Turbat",	"Bela",	"Bela",	"Pattala",	"Pattala",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chittor",	"Chittor",	"Ajmer",	"Ajmer",	"Gwalior",	"Gwalior",	"Khajuraho",	"Khajuraho",	"Sarabhanga",	"Sarabhanga",	"-1",	"-1",	"-1",	"Kharagpur",	"Tamralipti",	"Tamralipti",	"Kolikata",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Siemao",	"Siemao",	"-1",	"Twen Hia",	"Twen Hia",	"Cao Hanh",	"Cao Hanh",	"Lang Son",	"Lang Son",	"Hob Pho",	"Hob Pho",	"Tu Wan",	"Tu Wan",	"Kaoping",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Thubactis",	"Macomedes",	"-1",	"-1",	"-1",	"-1",	"Corniclanum",	"-1",	"-1",	"-1",	"-1",	"Ardanis Portus",	"Zygrae",	"Paraetonium",	"Paraetonium",	"Mareotis",	"Mareotis",	"Alexandreia",	"Alexandreia",	"Heliopolis",	"Heliopolis",	"Pelusion",	"-1",	"-1",	"Pharan",	"Pharan",	"-1",	"Taboo",	"Taboo",	"Tiamat",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ikaros",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dagaseira",	"Talmena",	"Talmena",	"Gwadar",	"Gwadar",	"Kysa",	"Kysa",	"-1",	"Bela",	"Debal",	"-1",	"-1",	"-1",	"-1",	"-1",	"Anhilwara",	"Anhilwara",	"Chittor",	"Chittor",	"Puskara",	"Puskara",	"Pabmavati",	"Pabmavati",	"Khajuraho",	"Khajuraho",	"Sarabhanga",	"Sarabhanga",	"-1",	"Bhodgaya",	"-1",	"Kharagpur",	"Tamralipti",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pugam",	"Pugam",	"-1",	"-1",	"-1",	"-1",	"Tsenghung",	"Tsenghung",	"Dien Bien Phu",	"Dien Bien Phu",	"Co Loa",	"Co Loa",	"Lang Son",	"-1",	"-1",	"-1",	"Tu Wan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Cydamus",	"Cydamus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Macomedes",	"Macomedes",	"Banadedari",	"Banadedari",	"Automala",	"Corniclanum",	"-1",	"-1",	"-1",	"-1",	"-1",	"Zygrae",	"Paraetonium",	"Paraetonium",	"Mareotis",	"-1",	"-1",	"-1",	"Herakleopolis Megale",	"Herakleopolis Megale",	"-1",	"-1",	"-1",	"Pharan",	"Pharan",	"-1",	"Taboo",	"Taboo",	"Hegra",	"Khaybar",	"Khaybar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Debal",	"-1",	"-1",	"-1",	"-1",	"-1",	"Anhilwara",	"Anhilwara",	"Udayapuri",	"Udayapuri",	"Ujjain",	"Ujjain",	"Vidisa",	"Vidisa",	"Bharhut",	"Bharhut",	"Asura",	"Asura",	"-1",	"-1",	"-1",	"Bhadrakh",	"Tamralipti",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pugam",	"Pugam",	"-1",	"-1",	"-1",	"-1",	"Tsenghung",	"Tsenghung",	"Dien Bien Phu",	"Dien Bien Phu",	"Co Loa",	"Co Loa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Cydamus",	"Cydamus",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ammonium",	"Ammonium",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hermopolis Megale",	"Hermopolis Megale",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Duba",	"Duba",	"Dedan",	"Yathreb",	"Yathreb",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gerrha",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Vadodara",	"Vadodara",	"Ashapalli",	"Udayapuri",	"Udayapuri",	"Ujjain",	"Ujjain",	"Vidisa",	"Vidisa",	"Bharhut",	"Bharhut",	"Asura",	"Asura",	"Toshali",	"Toshali",	"-1",	"Bhubaneshwar",	"Bhadrakh",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chiang Mai",	"Chiang Mai",	"-1",	"Luang Prabang",	"Ninh Kwang",	"Than Hoa",	"Than Hoa",	"-1",	"-1",	"-1",	"Tam A",	"Tam A",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ammonium",	"Ammonium",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ptolemais Hermiou",	"Diospolis",	"Diospolis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Duba",	"Dedan",	"Yathreb",	"Yathreb",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gerrha",	"Gerrha",	"-1",	"-1",	"-1",	"Sohar",	"Sohar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Dwarka",	"Valabhi",	"Valabhi",	"Saraswatapura",	"-1",	"Vadodara",	"Bharuch",	"Surpana",	"Surpana",	"Mahismati",	"Mahismati",	"Viswapuri",	"Viswapuri",	"Sarabhanga",	"Sarabhanga",	"-1",	"-1",	"Toshali",	"-1",	"Bhubaneshwar",	"Bhubaneshwar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chiang Mai",	"Chiang Mai",	"Luang Prabang",	"Luang Prabang",	"Ninh Kwang",	"Than Hoa",	"Than Hoa",	"-1",	"-1",	"Tam A",	"Tam A",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Oasis Magna",	"Oasis Magna",	"Ptolemais Hermiou",	"Diospolis",	"Diospolis",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Yanbu",	"Yanbu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tawam",	"Tawam",	"Sohar",	"Sohar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Somnath",	"-1",	"-1",	"-1",	"-1",	"Bharuch",	"Surpana",	"Surpana",	"Bhojakata",	"Bhojakata",	"Viswapuri",	"Kundinapuri",	"Kundinapuri",	"Sripura",	"Sripura",	"-1",	"-1",	"Singhapura",	"Singhapura",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Nan",	"Nan",	"-1",	"Viang Chang",	"Viang Chang",	"Ha Tinh",	"Ha Tinh",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Oasis Magna",	"Oasis Magna",	"-1",	"Apollinopolis",	"Apollinopolis",	"Omboi",	"-1",	"-1",	"Berenike Troglodytika",	"-1",	"-1",	"-1",	"-1",	"Johfa",	"Johfa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Milh",	"Milh",	"Tawam",	"Moscha",	"Moscha",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Palitana",	"-1",	"-1",	"-1",	"Janasthana",	"Janasthana",	"Bhojakata",	"Bhojakata",	"Shrishailam",	"Kundinapuri",	"Kundinapuri",	"Sripura",	"Sripura",	"-1",	"Kakinada",	"Singhapura",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Nan",	"-1",	"-1",	"Viang Chang",	"Viang Chang",	"Viang Chang",	"Ha Tinh",	"Ha Tinh",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Apollinopolis",	"Syene",	"Syene",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bakkah",	"Bakkah",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Moscha",	"Ibra",	"Ibra",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Surparaka",	"Surparaka",	"Rastrika",	"Janasthana",	"Pratishthana",	"Pratishthana",	"Shrishailam",	"Shrishailam",	"Sarabhapura",	"Sarabhapura",	"Vishakhapatanam",	"Kakinada",	"Kakinada",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Paigu",	"Paigu",	"Thaton",	"Thaton",	"-1",	"Sukothaya",	"Sukothaya",	"Sukothaya",	"-1",	"Phimai",	"Phimai",	"Preah Vhear",	"Preah Vhear",	"Hue",	"Hue",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Laoag",	"Laoag",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Phrim",	"Hierasykaminos",	"Hierasykaminos",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bakkah",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ibra",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Surparaka",	"Surparaka",	"Rastrika",	"Rastrika",	"Pratishthana",	"Pratishthana",	"Suvarnagiri",	"Suvarnagiri",	"Sarabhapura",	"Sarabhapura",	"Vishakhapatanam",	"Vishakhapatanam",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Paigu",	"Paigu",	"Thaton",	"Thaton",	"-1",	"-1",	"Sukothaya",	"Sri Thep",	"Phimai",	"Phimai",	"Preah Vhear",	"Preah Vhear",	"Preah Vhear",	"Hue",	"Hue",	"Hue",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Laoag",	"Laoag",	"Laoag",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Buhen",	"Para",	"Phrim",	"Phrim",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Turabah",	"Turabah",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Asich",	"Asich",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Vijayadurga",	"Vijayadurga",	"Kolhapur",	"Kolhapur",	"Vatapi",	"Vatapi",	"Suvarnagiri",	"Suvarnagiri",	"Nagarjunakonda",	"Vengi",	"Amaravati",	"Amaravati",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Paigu",	"Paigu",	"-1",	"Martaban",	"Martaban",	"-1",	"-1",	"Sri Thep",	"Banteay Chmar",	"Angkor",	"Angkor",	"Muang Kong",	"Muang Kong",	"Da Nang",	"Da Nang",	"Da Nang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lingayen",	"Lingayen",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tungul",	"Tungul",	"Buhen",	"Para",	"Para",	"-1",	"-1",	"Gebeit",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Turabah",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Murbat",	"Murbat",	"Asich",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Vijayadurga",	"Vijayadurga",	"Kolhapur",	"Kolhapur",	"Vatapi",	"Vatapi",	"Anantapur",	"Anantapur",	"Nagarjunakonda",	"Vengi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Martaban",	"-1",	"-1",	"-1",	"-1",	"Banteay Chmar",	"Angkor",	"Angkor",	"Muang Kong",	"Muang Kong",	"Da Nang",	"-1",	"-1",	"Da Nang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Seludong",	"Seludong",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tungul",	"Tungul",	"Semna",	"Kurgus",	"Kurgus",	"Kurgus",	"-1",	"Gebeit",	"Gebeit",	"-1",	"Isukib",	"-1",	"-1",	"-1",	"-1",	"Najran",	"Najran",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Murbat",	"Murbat",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Govapuri",	"-1",	"Vanavasi",	"Srirangapattana",	"Srirangapattana",	"Anantapur",	"Anantapur",	"Arikamedu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ayutthaya",	"Ayutthaya",	"Lavapura",	"Lavapura",	"Angkor",	"Muang Kong",	"Kompong Svay",	"Kompong Svay",	"Vijaya",	"Vijaya",	"Vijaya",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Seludong",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tungul",	"Tungul",	"Napata",	"Napata",	"Kurgus",	"Derudeb",	"Derudeb",	"Haiya",	"Haiya",	"Nakfa",	"Nakfa",	"-1",	"-1",	"-1",	"Najran",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Samharm",	"Samharm",	"Ubar",	"Ubar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Govapuri",	"Vanavasi",	"Vanavasi",	"Srirangapattana",	"Srirangapattana",	"Katapa",	"Katapa",	"Arikamedu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Ayutthaya",	"Ayutthaya",	"Lavapura",	"Lavapura",	"-1",	"Vat Nokor",	"Kompong Svay",	"Kompong Svay",	"Vijaya",	"Vijaya",	"Vijaya",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tondo",	"Tondo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tungul",	"Tungul",	"Napata",	"Medewi",	"Medewi",	"Derudeb",	"Derudeb",	"Haiya",	"Haiya",	"Haiya",	"Zula",	"-1",	"-1",	"-1",	"Azal",	"Azal",	"Ma'rib",	"Ma'rib",	"-1",	"-1",	"Qana",	"Qana",	"Samharm",	"Samharm",	"Ubar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gomantaka",	"-1",	"-1",	"Talakadu",	"Talakadu",	"Katapa",	"Katapa",	"Srikalahasti",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Rat Buri",	"Rat Buri",	"-1",	"Vat Banon",	"Vat Banon",	"-1",	"Vat Nokor",	"Vat Nokor",	"Vat Nokor",	"Kauthara",	"Kauthara",	"Kauthara",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Debba",	"Debba",	"Debba",	"Medewi",	"Medewi",	"Teawa",	"Teawa",	"Teawa",	"Infraz",	"Infraz",	"Qohaito",	"Zula",	"-1",	"-1",	"Azal",	"Azal",	"Ma'rib",	"Ma'rib",	"Shabwa",	"Shabwa",	"Qana",	"Qana",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Gomantaka",	"Vanchi",	"-1",	"Talakadu",	"Kolar",	"Kolar",	"Srinagam",	"Kaveripattinam",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Muang Sing",	"Muang Sing",	"-1",	"-1",	"Vat Banon",	"Vat Banon",	"Vat Banon",	"-1",	"Vat Nokor",	"Vat Nokor",	"-1",	"Kauthara",	"Kauthara",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Shendi",	"Shendi",	"Medewi",	"Teawa",	"Teawa",	"Gwandar",	"Axum",	"Axum",	"Wiqro",	"Asab",	"-1",	"-1",	"Zafar",	"Zafar",	"Timna",	"Timna",	"Shabwa",	"Shabwa",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Vanchi",	"Vanchi",	"-1",	"Karur",	"Karur",	"Srinagam",	"Kaveripattinam",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Muang Sing",	"-1",	"-1",	"-1",	"-1",	"-1",	"Phnom Chisor",	"Phnom Chisor",	"Prey Nokor",	"Prey Nokor",	"Prey Nokor",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Palawan",	"-1",	"-1",	"Iloilo",	"Iloilo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Shendi",	"Shendi",	"Shendi",	"Aborepi",	"Aborepi",	"Gwandar",	"Bahar Dar",	"Roha",	"Roha",	"Wiqro",	"Obock",	"-1",	"-1",	"Aden",	"Timna",	"Timna",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mohodayapuri",	"Mohodayapuri",	"-1",	"Talavanapura",	"Karur",	"Uraiyur",	"Kanchipuram",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chaiya",	"-1",	"-1",	"-1",	"-1",	"-1",	"Phnom Chisor",	"O Keo",	"Prey Nokor",	"Prey Nokor",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Palawan",	"-1",	"-1",	"Iloilo",	"Iloilo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Wad Naqa",	"Naqa",	"Naqa",	"Assosa",	"Assosa",	"Bahar Dar",	"Bahar Dar",	"Roha",	"Roha",	"Gewane",	"Obock",	"Obock",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Mohodayapuri",	"-1",	"Talavanapura",	"Uraiyur",	"Tiruchirappalli",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Chaiya",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"O Keo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Wad Naqa",	"Naqa",	"Naqa",	"Sennar",	"Sennar",	"Injibara",	"Mankorar",	"Mankorar",	"Awash",	"Gewane",	"Zeila",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Korkai",	"-1",	 "Kumari",	"Madurai",	"Madurai",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tambralinga",	"Tambralinga",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Soba",	"Soba",	"Tongo",	"Sennar",	"Injibara",	"Injibara",	"Debre Berhan",	"Debre Berhan",	"Awash",	"Awash",	"Zeila",	"Zeila",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Guardafui",	"Guardafui",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Korkai",	"-1",	"Madurai",	"-1",	"-1",	"Anuradhapura",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tambralinga",	"Tambralinga",	"Singhala",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Soba",	"Soba",	"Tongo",	"Tongo",	"Nekemte",	"Nekemte",	"Debre Berhan",	"Debre Berhan",	"Dire Dawa",	"Dire Dawa",	"Malao",	"Malao",	"Malao",	"Mundus",	"Mundus",	"Maydh",	"Maydh",	"-1",	"-1",	"Guardafui",	"Guardafui",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	 "Mohodayapuri",	 "Mohodayapuri",	"-1",	"-1",	"Anuradhapura",	"Anuradhapura",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Singhala",	"Singhala",	"Patalung",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Haggaro",	"Haggaro",	"-1",	"Fil Wiha",	"Fil Wiha",	"Dire Dawa",	"Harar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Tabae",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kelaniya",	"Katharagama",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kelantan",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Haggaro",	"Haggaro",	"Hirmata",	"Hirmata",	"Asella",	"-1",	"Harar",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Pano",	"Pano",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Kelaniya",	"Katharagama",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Lamuri",	"Lamuri",	"Perlak",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Melaka",	"-1",	"Trengganu",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Poni",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bonga",	"Bonga",	"Hirmata",	"Hirmata",	"Asella",	"Asella",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Opone",	"Opone",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Perlak",	"Perlak",	"-1",	"-1",	"-1",	"-1",	"-1",	"Melaka",	"-1",	"Pahang",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Maling",	"Poni",	"Poni",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Bonga",	"Bonga",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hobyo",	"Opone",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Barus",	"Barus",	"-1",	"-1",	"-1",	"Pane",	"-1",	"-1",	"-1",	"Kota Gelanggi",	"Kota Gelanggi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sarawak",	"Maling",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Hobyo",	"Hobyo",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Barus",	"-1",	"-1",	"-1",	"Pane",	"Pane",	"-1",	"-1",	"-1",	"Kota Gelanggi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sarawak",	"Sarawak",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	),
(	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Sarapion",	"Sarapion",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"Jambi",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	"-1",	))

# dictionaries override default names; repetitions are needed in case of reconquest

lCityNames = [
# 0: Medieval Greek
{
	"Konstantinoupolis" : "Konstantinoupolis",
	"Ankyra" : "Ankyra",
	"Ikonion" : "Ikonion",
	"Adrianoupolis" : "Adrianoupolis",
	"Sinopi" : "Sinopi",
	"Smyrna" : "Smyrna",
	"Dorylaion" : "Dorylaion",
	"Antioch" : "Antiocheia",
	"Kaisareia" : "Kaisareia",
	"Sevasteia" : "Sevasteia",
	"Amastris" : "Amastris",
	"Attaleia" : "Attaleia",
	"Philippoupolis" : "Philippoupolis",
	"Prousa" : "Prousa",
	"Sur" : "Tyros",
	"Al-Quds" : "Hierosolyma",
	"Tarsos" : "Tarsos",
	"Manzikert" : "Manzikert",
	"Dimashq" : "Damaskos",
	"Rodos" : "Rodos",
	"Famagusta" : "Famagusta",
	"Alexandria" : "Alexandreia",
	"Tungul" : "Dongola",
	"Para" : "Faras",
	"Akka" : "Acre",
	"Al-Majdal" : "Askalon",
	"Sayda" : "Sidon",
	"Arsaaf" : "Arsuf",
	"Tarabulus" : "Tripolis",
	"Alexandretta" : "Alexandretta",
	"Mamistra" : "Mamistra",
	"Nikomedia" : "Nikomedia",
	"Nikaia" : "Nikaia",
	"Philadelphia" : "Philadelphia",
	"Sampsounta" : "Sampsounta",
	"Koloneia" : "Koloneia",
	"Laranda" : "Laranda",
	"Archelais" : "Archelais",
	"Ghazza" : "Gaza",
	"Efesos" : "Efesos",
	"Kallipolis" : "Kallipolis",
	"Dardanellia" : "Dardanellia",
	"Abydos" : "Abydos",
	"Amida" : "Amida",
	"Herakleia" : "Herakleia",
	"Timonion" : "Timonion",
	"Selinus" : "Selinus",
	"Amaseia" : "Amaseia",
	"Palaeokastron" : "Palaeokastron",
	"Melitene" : "Malateia",
	"Damietta" : "Tamiathis",
	"Tralleis" : "Tralleis",
	"Trapezounta" : "Trapezounta",
	"Kalonoros" : "Kalonoros",
	"Kokison" : "Kokison",
	"Semsur" : "Perre",
	"Edessa" : "Ioustinoupolis",
	"Karin" : "Theodosioupolis",
	"Kharput" : "Kharput",
	"Kandari" : "Kandari",
	"Sis" : "Sision",
	"Philomelion" : "Philomelion",
	"Seleukeia" : "Seleukeia",
	"Kotyaion" : "Kotyaion",
	"Al-Mosul" : "Mosul",
	"An-Najaf" : "Najaf",
	"Al-Kufah" : "Kufa",
	"Al-Basrah" : "Basra",
	"Bagdad" : "Bagdad",
	"Rayy" : "Rhagai",
	"Marash" : "Germanikeia",
	"Nikopolis" : "Nikopolis",
	"Nisibin" : "Nisibis",
	"Tigranakert" : "Martyropolis",
	"Ar-Raqqah" : "Kallinikos",
	"Homs" : "Emesa",
	"Saveh" : "Sava",
	"Alikarnassos" : "Alikarnassos",
	"Tartus" : "Antarados",
	"Byblos" : "Byblos",
	"Poti" : "Phasis",
	"Kutaisi" : "Aias",
	"Halab" : "Verria",
	"Latakia" : "Laodikeia",
	"Eutokia" : "Eutokia",
	"Harran" : "Hellenoupolis",
	"Amorion" : "Amorion",
	"Fayyum" : "Phiom",
	"Lefkousia" : "Lefkousia",
},
# 1: Nubian
{
	"Tungul" : "Tungul",
	"Para" : "Para",
	"Phrim" : "Phrim",
	"Kalabsha" : "Kalabsha",
	"Mero&#235;" : "Mero&#235;",
	"Fayyum" : "Phiom",
},
# 2: Arabic/Persian
{
	"Konstantinoupolis" : "Qustantiniyah",
	"Sur" : "Sur",
	"Akka" : "Akka",
	"Al-Quds" : "Al-Quds",
	"Antioch" : "Antakiyya",
	"Halab" : "Halab",
	"Tarsos" : "Tarsos",
	"Dvin" : "Dabil",
	"Dimashq" : "Dimashq",
	"Alexandria" : "Al-Iskandariyya",
	"Alexandretta" : "Al-Iskandarun",
	"Para" : "Faras",
	"Phrim" : "Qasr Ibrim",
	"Tungul" : "Dunqulah",
	"Al-Qahira" : "Al-Qahira",
	"Tarabulus" : "Tarabulus",
	"Ghazza" : "Ghazza",
	"Al-Majdal" : "Al-Majdal",
	"Sayda" : "Sayda",
	"Yafa" : "Yafa",
	"Karak" : "Karak",
	"Ganjeh" : "Ganjeh",
	"Amida" : "Diyar-i Bekr",
	"Damietta" : "Domyat",
	"Dhillika" : "Dilli",
	"Manbai" : "Manbai",
	"Kaisereia" : "Kaisariyah",
	"Edessa" : "Ar-Raha",
	"Ar-Raqqah" : "Ar-Raqqah",
	"Madinah" : "Madinah",
	"Makkah" : "Makkah",
	"Al-Aqabah" : "Al-Aqabah",
	"Al-Mosul" : "Al-Mosul",
	"An-Najaf" : "An-Najaf",
	"Al-Basrah" : "Al-Basrah",
	"Bagdad" : "Bagdad",
	"Masqat" : "Masqat",
	"Karin" : "Kalikala",
	"Purushapura" : "Peshawar",
	"Luxor" : "Al-Uqsur",
	"Minya" : "Al-Minya",
	"Arish" : "Al-Arish",
	"Mero&#235;" : "Meruwah",
	"Teawa" : "Al-Qadarif",
	"Rayy" : "Rayy",
	"Tigranakert" : "Mayyafariqin",
	"Marash" : "Maras",
	"Homs" : "Homs",
	"Saveh" : "Saveh",
	"Goa" : "Sindapur",
	"Nishapur" : "Neyshabur",
	"Al-Qatif" : "Al-Qatif",
	"Tartus" : "Tartus",
	"Byblos" : "Byblos",
	"Kalabsha" : "Bab al-Kalabsha",
	"Sevasteia" : "Sebhasd",
	"Trapezounta" : "Tarabizun",
	"Latakia" : "Al-Ladhiqiyyah",
	"Harran" : "Harran",
	"Semsur" : "Hisn-i Mansur",
	"Amorion" : "Ammuriye",
	"Lavapuri" : "Lahore",
},
# 3: Turkish
{
	"Konstantinoupolis" : "Kostantiniyye",
	"Ankyra" : "Angora",
	"Ikonion" : "Konya",
	"Adrianoupolis" : "Edrene",
	"Sinopi" : "Sinop",
	"Trapezounta" : "Trabzon",
	"Smyrna" : "Izmir",
	"Dorylaion" : "Eskisehir",
	"Antioch" : "Antakya",
	"Kaisareia" : "Kayseri",
	"Sevasteia" : "Sivas",
	"Amastris" : "Amasra",
	"Attaleia" : "Adalya",
	"Manzikert" : "Malazgirt",
	"Prousa" : "Brusa",
	"Al-Quds" : "Kud&#252;s",
	"Rodos" : "Rodos",
	"Famagusta" : "Magusa",
	"Alexandria" : "Iskenderiye",
	"Al-Qahira" : "Kahire",
	"Tarabulus" : "Trablussam",
	"Alexandretta" : "Iskenderun",
	"Mamistra" : "Misis",
	"Nikomedia" : "Iznikmid",
	"Nikaia" : "Iznit",
	"Philadelphia" : "Alasehir",
	"Sampsounta" : "Samsun",
	"Koloneia" : "Sebinkarahisar",
	"Laranda" : "Karaman",
	"Archelais" : "Aksaray",
	"Efesos" : "Selcuk",
	"Kallipolis" : "Gelibolu",
	"Dardanellia" : "Canakkale",
	"Abydos" : "Canakkale",
	"Herakleia" : "Eregli",
	"Timonion" : "Kastamonu",
	"Selinus" : "Gazipasa",
	"Amaseia" : "Amasya",
	"Palaeokastron" : "Balikesir",
	"Melitene" : "Malatya",
	"Naxchivan" : "Naxchivan",
	"Tralleis" : "Aydin",
	"Kalonoros" : "Alaiye",
	"Kokison" : "Goksun",
	"Semsur" : "Adiyaman",
	"Edessa" : "Urfa",
	"Karin" : "Erzurum",
	"Yerzka" : "Erzincan",
	"Ar-Raqqah" : "Rakka",
	"Kharput" : "Elazig",
	"Kandari" : "Kankiri",
	"Sis" : "Sision",
	"Philomelion" : "Aksehir",
	"Seleukeia" : "Silifke",
	"Kotyaion" : "Kutahya",
	"Al-Mosul" : "Musul",
	"An-Najaf" : "Necef",
	"Dhillika" : "Dilli",
	"Ajayameru" : "Ajmer",
	"Manbai" : "Manbai",
	"Dharanagara" : "Dhar",
	"Mandavgarh" : "Shadiabad",
	"Bhojpal" : "Bhopal",
	"Somnath" : "Veraval",
	"Bhingar" : "Ahmednagar",
	"Al-Aqabah" : "Aqaba",
	"Purushapura" : "Peshawar",
	"Rayy" : "Rayy",
	"Van" : "Van",
	"Mardin" : "Mardin",
	"Marash" : "Maras",
	"Amida" : "Diyar-i Bekr",
	"Nikopolis" : "Afyon",
	"Khlat" : "Ahlat",
	"Tigranakert" : "Silvan",
	"Homs" : "Humus",
	"Nishapur" : "Neyshabur",
	"Alikarnassos" : "Bodrum",
	"Poti" : "Fas",
	"Kutaisi" : "Kutais",
	"Halab" : "Halep",
	"Makkah" : "Mekke",
	"Madinah" : "Medine",
	"Latakia" : "Lazkiye",
	"Eutokia" : "Tokat",
	"Harran" : "Harran",
	"Amorion" : "Hergen Kale",
	"Lefkousia" : "Lefkosa",
	"Lavapuri" : "Lahore",
},
# 4: Armenian
{
	"Manzikert" : "Manazkert",
	"Dvin" : "Dvin",
	"Sur" : "Tyre",
	"Al-Quds" : "Hierosolyma",
	"Antioch" : "Antioch",
	"Tarsos" : "Tarson",
	"Melitene" : "Malatya",
	"Alexandria" : "Alexandria",
	"Damietta" : "Damietta",
	"Mamistra" : "Mamistra",
	"Ganjeh" : "Gandzak",
	"Naxchivan" : "Nakhchivan",
	"Tralleis" : "Tralleis",
	"Trapezounta" : "Trapizon",
	"Kokison" : "Kokison",
	"Perre" : "Perre",
	"Kaisareia" : "Mazak",
	"Sevasteia" : "Sebaste",
	"Edessa" : "Urhai",
	"Derbent" : "Daruband",
	"Yerznka" : "Yerznka",
	"Karin" : "Karin",
	"Kharput" : "Kharput",
	"Sis" : "Sis",
	"Seleukeia" : "Seleukeia",
	"Kalonoros" : "Kalonoros",
	"Kars" : "Kars",
	"Rayy" : "Rages",
	"Attaleia" : "Antalia",
	"Prousa" : "Boursa",
	"Van" : "Van",
	"Sinopi" : "Sinop",
	"Sampsounta" : "Samsoun",
	"Mardin" : "Merdin",
	"Marash" : "Maras",
	"Amida" : "Diarbekir",
	"Nisibin" : "Mtsbin",
	"Khlat" : "Khlat",
	"Tigranakert" : "Tigranakert",
	"Halab" : "Halep",
	"Harran" : "Harran",
},
# 5: Georgian
{
	"Manzikert" : "Manazkert",
	"Dvin" : "Dvin",
	"Sur" : "Tyre",
	"Al-Quds" : "Hierosolyma",
	"Antioch" : "Antioch",
	"Tarsos" : "Tarson",
	"Melitene" : "Malatya",
	"Alexandria" : "Alexandria",
	"Damietta" : "Damietta",
	"Mamistra" : "Mamistra",
	"Ganjeh" : "Gandzak",
	"Naxchivan" : "Nakhchivan",
	"Tralleis" : "Tralleis",
	"Trapezounta" : "T'rap'izoni",
	"Kokison" : "Kokison",
	"Perre" : "Perre",
	"Kaisareia" : "Mazak",
	"Sevasteia" : "Sivasi",
	"Edessa" : "Urhai",
	"Derbent" : "Daruband",
	"Yerznka" : "Yerznka",
	"Karin" : "Karin",
	"Kharput" : "Kharput",
	"Sis" : "Sis",
	"Seleukeia" : "Seleukeia",
	"Kalonoros" : "Kalonoros",
	"Kars" : "Qarsi",
	"Rayy" : "Rages",
	"Attaleia" : "Antalia",
	"Van" : "Vani",
	"Sinopi" : "Sinopi",
	"Sampsounta" : "Samsuni",
	"Mardin" : "Mardini",
	"Kaisareia" : "Kaiseri",
	"Marash" : "Marasi",
	"Amida" : "Diarbakiri",
	"Khlat" : "Khlat",
	"Poti" : "Poti",
	"Kutaisi" : "Kutaisi",
	"Harran" : "Harran",
},
# 6: Outremer/Latin
{
	"Sur" : "Tyre",
	"Al-Quds" : "Hierosolyma",
	"Antioch" : "Antiochia",
	"Tarsos" : "Tarsus",
	"Dimashq" : "Damascus",
	"Famagusta" : "Famagusta",
	"Alexandria" : "Alexandria",
	"Al-Qahira" : "Cairo",
	"Konstantinoupolis" : "Constantinopolis",
	"Akka" : "Acre",
	"Ghazza" : "Gaza",
	"Al-Majdal" : "Ascalon",
	"Sayda" : "Sidon",
	"Arsaaf" : "Arsuf",
	"Tarabulus" : "Tripoli",
	"Alexandretta" : "Alexandretta",
	"Karak" : "Kerak",
	"Mamistra" : "Mamistra",
	"Attaleia" : "Attalia",
	"Kaisareia" : "Caesarea Mazaca",
	"Nikaia" : "Nicaea",
	"Philadelphia" : "Philadelphia",
	"Damietta" : "Damietta",
	"Tralleis" : "Tralles",
	"Trapezounta" : "Trapezounta",
	"Dhillika" : "Delhi",
	"Manbai" : "Bombaim",
	"Kalonoros" : "Candelore",
	"Para" : "Pachoras",
	"Ankyra" : "Ancyra",
	"Ikonion" : "Iconium",
	"Kokison" : "Coxon",
	"Perre" : "Perre",
	"Edessa" : "Edessa",
	"Kharput" : "Kharput",
	"Sis" : "Sisium",
	"Seleukeia" : "Seleucia Trachea",
	"Al-Mosul" : "Mosul",
	"An-Najaf" : "Najaf",
	"Al-Kufah" : "Kufa",
	"Al-Basrah" : "Basra",
	"Bagdad" : "Baghdad",
	"Madinah" : "Medina",
	"Makkah" : "Mecca",
	"Al-Aqabah" : "Aqaba",
	"Masqat" : "Mascate",
	"Adrianoupolis" : "Hadrianopolis",
	"Sampsounta" : "Amisus",
	"Rodos" : "Rodi",
	"Efesos" : "Ephesus",
	"Melitene" : "Melitene",
	"Sevasteia" : "Sebastea",
	"Rayy" : "Rhagae",
	"Marash" : "Germanicia",
	"Amida" : "Amida",
	"Nisibin" : "Nisibis",
	"Manzikert" : "Manzikert",
	"Tigranakert" : "Tigranocerta",
	"Ar-Raqqah" : "Callinicum",
	"Homs" : "La Chamelle",
	"Saveh" : "Saba",
	"Goa" : "Goa",
	"Alikarnassos" : "Petronium",
	"Al-Qatif" : "Catifa",
	"Tartus" : "Tortosa",
	"Byblos" : "Gibelet",
	"Somnath" : "Diu",
	"Halab" : "Alep",
	"Latakia" : "Laodicea",
	"Harran" : "Hellenopolis",
	"Amorion" : "Amorium",
	"Lefkousia" : "Nicosia",
},
# 7: Hindu
{
	"Dhillika" : "Dilli",
	"Manbai" : "Manbai",
	"Goa" : "Sindapur",
	"Nishapur" : "Nishapur",
	"Somnath" : "Somnath",
	"Mansura" : "Mansura",
	"Lavapuri" : "Lahore",
	"Mandavgarh" : "Mandavgarh",
},
]


class CityNameManager:


	def getLanguages(self, iCiv):
		"""Determines the primary and secondary language for use with lCityNames."""
		
		iPrimary = 0
		iSecondary = 1
		
		return (iPrimary, iSecondary)


	def assignName(self, city):
		"""Names a city depending on its plot."""
		
		iOwner = city.getOwner()
		cityName = tCityMap[gc.getMap().getGridHeight() - city.getY() - 1][city.getX()]
		if cityName != "-1":
			# check if the default name is in dictionary, if yes, use it; otherwise use default
			iPrimary, iSecondary = self.getLanguages(iOwner)
			if cityName in lCityNames[iPrimary]:
				city.setName(lCityNames[iPrimary][cityName], False)
			elif cityName in lCityNames[iSecondary]:
				city.setName(lCityNames[iSecondary][cityName], False)
			else:
				city.setName(cityName, False)


	def renameCity(self, city, iNewOwner):
		"""Renames a city depending on its owner."""
		
		# skip Sur in Oman
		if city.getX() == 63 and city.getY() == 17:
			return
		
		mapName = tCityMap[gc.getMap().getGridHeight() - city.getY() - 1][city.getX()]
		
		# ignore independents and barbarians
		if iNewOwner < iNumPlayers:
			# check if the default name is in dictionary, if yes, rename the city
			iPrimary, iSecondary = self.getLanguages(iNewOwner)
			if mapName in lCityNames[iPrimary]:
				city.setName(lCityNames[iPrimary][mapName], False)
			elif mapName in lCityNames[iSecondary]:
				city.setName(lCityNames[iSecondary][mapName], False)